### ISSUE TITLE
0.18.0 - JS error - SyntaxError: No node type or group 'listItem' found

### ISSUE THREAD

**Issue by jsa34** [feincms/django-prose-editor#54]
Since updating to v0.18.0 from v0.17.0, I am seeing this JS error on pages using the Django Prose Editor:

```javascript
configurable.js:94 Error initializing prose editor: SyntaxError: No node type or group 'listItem' found (in content expression 'listItem+')
    at P.err (index.js:1797:26)
    at index.js:1859:16
    at index.js:1861:1
    at index.js:1883:1
    at index.js:1828:1
    at e (index.js:1812:1)
    at I.parse (index.js:1805:1)
    at new K (index.js:2441:63)
    at o1 (index.js:757:10)
    at new iG (index.js:2106:19)

  | (anonymous) | @ | configurable.js:94

  | Promise.catch |   |  
  | a | @ | configurable.js:93
  | r | @ | editor.js:85
  | pt | @ | editor.js:99
  | (anonymous) | @ | configurable.js:108

```

Example usage:
```python
from django_prose_editor.fields import ProseEditorField


class CustomProseEditorField(ProseEditorField):
    def __init__(self, *args, **kwargs):
        # Set the default class-level attributes to kwargs if they aren't already set
        kwargs.setdefault(
            "extensions",
            {
                "Bold": True,
                "Italic": True,
                "Underline": True,
                "BulletList": True,
                "OrderedList": True,
                "HardBreak": True,
                "Link": {
                    "enableTarget": True,
                },
                "Heading": {"levels": [1, 2, 3, 4, 5, 6]},
                "History": True,
                "HTML": False,
            },
        )
        kwargs.setdefault("sanitize", True)

        # Call the parent constructor
        super().__init__(*args, **kwargs)

class CustomModel(models.Model):
    literature_reviews = CustomProseEditorField(
        blank=True, null=True, verbose_name="literature reviews"
    )
```

**Comment by matthiask** [comment]
Hi @jsa34 

Yep, you have to add `"ListItem": True` as well. The dependency isn't added automatically anymore.

See here for more on why I changed this:
https://github.com/feincms/django-prose-editor/blob/main/CHANGELOG.rst#018-2025-08-27

By the way, you should have seen a warning to that effect in the `runserver` output:
https://github.com/feincms/django-prose-editor/blob/f76e1df0d35e9f15cad083842a4df845533aea73/django_prose_editor/config.py#L335-L338

Maybe you have a suggestion how this warning could be improved? I would have preferred to use more visible system checks but this configuration isn't exactly a problem normally.


Another issue: I think you have added `null=True` on purpose; Django doesn't use `NULL` ever on stringly typed fields, see https://docs.djangoproject.com/en/5.2/ref/databases/#null-and-empty-strings -- you may have good reasons to use this, anyway.
